flaskr/__init__.py
import os

from flask import Flask, render_template

def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),
    )


    from .blueprints import chat
    app.register_blueprint(chat.bp)
    
    return app

flaskr/blueprints/chat.py
import os
from flask import Blueprint, render_template, request, jsonify, redirect, url_for
import flaskr.openaiapi as op

bp = Blueprint('chat', __name__, url_prefix='')

@bp.route('/', methods=('POST', 'GET'))
def index():
    if request.method == 'POST':
        input = request.get_json()['question']
        answ = op.completion(input)
        return jsonify({'answer': answ['choices'][0]['message']['content']})
    return render_template('chat/index.html', system=op.messages[0]["content"], current_model=op.current_model, models=op.models)

@bp.route('/clear', methods=['GET'])
def clear():
    op.clear()
    return redirect(url_for('chat.index'))

@bp.route('/change_system', methods=['POST'])
def change_system():
    new_system = request.get_json()['system']
    op.define_system(new_system)
    return jsonify({})

@bp.route('/change_version', methods=['POST'])
def change_version():
    new_model = request.get_json()['version']
    op.change_version(new_model)
    print(op.current_model)
    return jsonify({})

flaskr/templates/chat/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Chat-GPT API</title>
    <link href="{{url_for('static', filename='bootstrap.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static', filename='highlight.min.css')}}">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>


</head>

<body>

    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

            <div class="container-fluid">
                <a class="navbar-brand" href="#">Chat GPT API</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">

                    </ul>
                </div>
                <div style="margin-right: 50%;">
                    <label for="select_version" style="color: aliceblue;">Select model:</label>
                    <select id="select_version" onchange="change_version()">
                        {% for version in models %}
                        {% if version == current_model %}
                        <option value="{{version}}" selected> {{version}} </option>
                        {% else %}
                        <option value="{{version}}"> {{version}} </option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <input id="change-system-input" value="{{system}}">
                    <button id="change-system-button" class="btn btn-primary">Change system</button>
                </div>
            </div>
        </nav>
    </header>

    <!-- Begin page content -->
    <main class="flex-shrink-0">
        <div class="container">
            <br>
            <br>
            <br>
            <br>

            <div id="list-group" class="list-group w-auto">

            </div>

            <div class="input-group mb-3">
                <textarea class="form-control" id="chat-input"
                    placeholder="Enter your text and ask with Shift+Enter or press the button"
                    style="height: 100px;"></textarea>
            </div>
            <div class="input-group-append">
                <button id="gpt-button" class="btn btn-primary">Ask ChatGPT</button>
                <button id="gpt-button-clear" class="btn btn-primary"
                    onclick=" location.href= '{{url_for('chat.clear')}}'">Clear context</button>
            </div>
    </main>


    <script>

        function change_version(){
            var version = document.getElementById("select_version").value;
            let data = { "version": version };
            fetch("{{ url_for('chat.change_version') }}", { "method": "POST", "headers": { "Content-Type": "application/json" }, "body": JSON.stringify(data) })
                .then(response => response.json())
                .then(data => {
                    location.reload();
                });
            
        }

        const buttonChangesystem = document.getElementById('change-system-button');
        buttonChangesystem.addEventListener('click', handler_changesystem);

        function handler_changesystem() {
            var system = document.getElementById("change-system-input").value;
            let data = { "system": system };
            fetch("{{ url_for('chat.change_system') }}", { "method": "POST", "headers": { "Content-Type": "application/json" }, "body": JSON.stringify(data) })
                .then(response => response.json())
                .then(data => {
                    location.reload();
                });
        };

        const button = document.getElementById('gpt-button');
        button.addEventListener('click', handler);


        const inp = document.getElementById('chat-input');
        inp.addEventListener('keydown', function (e) {
            if (e.key === 'Enter' && event.shiftKey) {
                handler();
            }
        });

        function handler() {
            var question = document.getElementById("chat-input").value;
            var listGroup = document.getElementById('list-group');
            document.getElementById("chat-input").value = "";
            listGroup.innerHTML += `
                                        <div class="d-flex gap-2 w-100 justify-content-between chat-user">
                                        <div>
                                            <p class="mb-0 opacity-75">${question.replace(/\n/g, '<br/>')}</p>
                                        </div>
                                        </div>
                                    `;
            let data = { "question": question };

            listGroup.innerHTML += `
                                <div class="d-flex gap-2 w-100 justify-content-between chat-gpt" id="loading">
                                    <div>
                                        <p class="mb-0 opacity-75">Thinking....</p>
                                    </div>
                                </div>
                            `;

            fetch("{{ url_for('chat.index') }}", { "method": "POST", "headers": { "Content-Type": "application/json" }, "body": JSON.stringify(data) })
                .then(response => response.json())
                .then(data => {

                    marked.setOptions({
                        highlight: function (code) {
                            return hljs.highlightAuto(code).value;
                        },
                        langPrefix: 'hljs language-',
                    });
                    var t = marked.parse(data.answer);
                    const divToRemove = document.getElementById('loading');
                    divToRemove.parentNode.removeChild(divToRemove);
                    listGroup.innerHTML += `
                                            <div class="d-flex gap-2 w-100 justify-content-between chat-gpt">
                                            <div>
                                            <p class="mb-0 opacity-75">${t}</p>
                                            </div>
                                        </div>
                            `;

                    hljs.highlightAll();
                });


        };
    </script>

</body>

</html>